INSERT INTO OAUTH_CLIENT_DETAILS (
	CLIENT_ID, 
	CLIENT_SECRET,
	SCOPE, 
	AUTHORIZED_GRANT_TYPES,
    WEB_SERVER_REDIRECT_URI, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY, ADDITIONAL_INFORMATION, AUTOAPPROVE)
VALUES (
	'cueva', 
	'{bcrypt}$2a$10$a.jUkhyX88ouqg4pNZk.ZOXRfjAlEDhwcyl35SifJzt6dKOH9tuAy', 
	'read,write',
	'password,authorization_code,refresh_token',
	null, null, 36000, 36000, null, true);

INSERT INTO USERS ( USERNAME, PASSWORD, ENABLED) VALUES ( 'marcelo@mail.com', '{bcrypt}$2a$10$PWZg7okfLhLcKMwUw.mOTOKA9vQTqFPp0ITOKx3gfSlLfOZe5iJVW', true );
INSERT INTO AUTHORITIES ( USERNAME, AUTHORITY) VALUES ( 'marcelo@mail.com', 'ROLE_ADMIN' );
INSERT INTO AUTHORITIES ( USERNAME, AUTHORITY) VALUES ( 'marcelo@mail.com', 'ROLE_USER' );

INSERT INTO USERS ( USERNAME, PASSWORD, ENABLED) VALUES ( 'biro@mail.com', '{bcrypt}$2a$10$PWZg7okfLhLcKMwUw.mOTOKA9vQTqFPp0ITOKx3gfSlLfOZe5iJVW', true );
INSERT INTO AUTHORITIES ( USERNAME, AUTHORITY) VALUES ( 'biro@mail.com', 'ROLE_USER' );

INSERT INTO USERS ( USERNAME, PASSWORD, ENABLED) VALUES ( 'eduardo@mail.com', '{bcrypt}$2a$10$PWZg7okfLhLcKMwUw.mOTOKA9vQTqFPp0ITOKx3gfSlLfOZe5iJVW', true );
INSERT INTO AUTHORITIES ( USERNAME, AUTHORITY) VALUES ( 'eduardo@mail.com', 'ROLE_USER' );

INSERT INTO USERS ( USERNAME, PASSWORD, ENABLED) VALUES ( 'will@mail.com', '{bcrypt}$2a$10$PWZg7okfLhLcKMwUw.mOTOKA9vQTqFPp0ITOKx3gfSlLfOZe5iJVW', true );
INSERT INTO AUTHORITIES ( USERNAME, AUTHORITY) VALUES ( 'will@mail.com', 'ROLE_USER' );

INSERT INTO USERS ( USERNAME, PASSWORD, ENABLED) VALUES ( 'gabi@mail.com', '{bcrypt}$2a$10$PWZg7okfLhLcKMwUw.mOTOKA9vQTqFPp0ITOKx3gfSlLfOZe5iJVW', true );
INSERT INTO AUTHORITIES ( USERNAME, AUTHORITY) VALUES ( 'gabi@mail.com', 'ROLE_USER' );

INSERT INTO USERS ( USERNAME, PASSWORD, ENABLED) VALUES ( 'carol@mail.com', '{bcrypt}$2a$10$PWZg7okfLhLcKMwUw.mOTOKA9vQTqFPp0ITOKx3gfSlLfOZe5iJVW', true );
INSERT INTO AUTHORITIES ( USERNAME, AUTHORITY) VALUES ( 'carol@mail.com', 'ROLE_USER' );

INSERT INTO USERS ( USERNAME, PASSWORD, ENABLED) VALUES ( 'rai@mail.com', '{bcrypt}$2a$10$PWZg7okfLhLcKMwUw.mOTOKA9vQTqFPp0ITOKx3gfSlLfOZe5iJVW', true );
INSERT INTO AUTHORITIES ( USERNAME, AUTHORITY) VALUES ( 'rai@mail.com', 'ROLE_USER' );

INSERT INTO USERS ( USERNAME, PASSWORD, ENABLED) VALUES ( 'jean@mail.com', '{bcrypt}$2a$10$PWZg7okfLhLcKMwUw.mOTOKA9vQTqFPp0ITOKx3gfSlLfOZe5iJVW', true );
INSERT INTO AUTHORITIES ( USERNAME, AUTHORITY) VALUES ( 'jean@mail.com', 'ROLE_USER' );

INSERT INTO USERS ( USERNAME, PASSWORD, ENABLED) VALUES ( 'gretchen@mail.com', '{bcrypt}$2a$10$PWZg7okfLhLcKMwUw.mOTOKA9vQTqFPp0ITOKx3gfSlLfOZe5iJVW', true );
INSERT INTO AUTHORITIES ( USERNAME, AUTHORITY) VALUES ( 'gretchen@mail.com', 'ROLE_USER' );

INSERT INTO USERS ( USERNAME, PASSWORD, ENABLED) VALUES ( 'fernando@mail.com', '{bcrypt}$2a$10$PWZg7okfLhLcKMwUw.mOTOKA9vQTqFPp0ITOKx3gfSlLfOZe5iJVW', true );
INSERT INTO AUTHORITIES ( USERNAME, AUTHORITY) VALUES ( 'fernando@mail.com', 'ROLE_USER' );

